#!/usr/bin/env python3
"""Wrap each lab's source in a .js file so a lesson page can read it.

Standard library only.

Why this exists: the in-browser lab runner needs the lab's source. A lesson
page opened straight from a downloaded folder cannot read a sibling .py file.
Tested in Chromium at file://, both routes are refused:

    fetch('lab.py')  TypeError: Failed to fetch
                     Fetch API cannot load ... URL scheme "file" is not supported
    XHR  'lab.py'    NetworkError: Failed to execute 'send' on 'XMLHttpRequest'

A <script src> tag is not refused, statically or injected at click time, so
each lab also ships as labs/<name>.lab.js assigning its source to a global.
The .py file stays the source of truth; this tool only copies it.

Usage:
    python3 tools/build_lab_bundles.py            # write labs/*.lab.js
    python3 tools/build_lab_bundles.py --check    # exit 1 if any is stale

--check is what keeps the two copies honest. Nothing else would notice a lab
edited without rebuilding, and a reader would then run different code from the
one the page publishes the output of.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LABS = ROOT / "labs"
SUFFIX = ".lab.js"

HEADER = ("// Generated by tools/build_lab_bundles.py from %s\n"
          "// Do not edit. The .py file is the source of truth.\n")


def labs():
    return sorted(p for p in LABS.glob("*.py"))


def bundle_for(path):
    """The exact bytes labs/<name>.lab.js should contain."""
    source = path.read_text(encoding="utf-8")
    return (HEADER % path.name
            + "window.__labSources = window.__labSources || {};\n"
            + "window.__labSources[%s] = %s;\n"
            % (json.dumps(path.name), json.dumps(source)))


def target_for(path):
    return LABS / (path.stem + SUFFIX)


def check():
    stale, missing, orphan = [], [], []
    expected = set()
    for path in labs():
        target = target_for(path)
        expected.add(target.name)
        if not target.is_file():
            missing.append(target.name)
        elif target.read_text(encoding="utf-8") != bundle_for(path):
            stale.append(target.name)
    for found in sorted(LABS.glob("*" + SUFFIX)):
        if found.name not in expected:
            orphan.append(found.name)

    print("build_lab_bundles --check")
    print("  labs                  %d" % len(labs()))
    print("  bundles up to date    %d" % (len(labs()) - len(stale) - len(missing)))
    print("  stale                 %d" % len(stale))
    print("  missing               %d" % len(missing))
    print("  orphaned              %d" % len(orphan))
    problems = ([("stale", n) for n in stale] + [("missing", n) for n in missing]
                + [("orphaned", n) for n in orphan])
    if problems:
        print("\nrun python3 tools/build_lab_bundles.py")
        for kind, name in problems[:20]:
            print("  %-9s labs/%s" % (kind, name))
        return 1
    print("\nevery lab bundle matches its .py file")
    return 0


def write():
    written = 0
    for path in labs():
        target = target_for(path)
        content = bundle_for(path)
        if not target.is_file() or target.read_text(encoding="utf-8") != content:
            target.write_text(content, encoding="utf-8")
            written += 1
    expected = {target_for(p).name for p in labs()}
    for found in sorted(LABS.glob("*" + SUFFIX)):
        if found.name not in expected:
            print("  orphaned bundle, delete it by hand: labs/%s" % found.name)
    print("wrote %d of %d lab bundles" % (written, len(labs())))
    return 0


def main():
    if "--check" in sys.argv[1:]:
        return check()
    return write()


if __name__ == "__main__":
    sys.exit(main())
