#!/usr/bin/env python3
"""Build the search index from content/ into assets/search-index.js.

Standard library only.

Why a .js file and not .json: a page opened from a downloaded folder cannot
fetch a sibling file, which tools/build_lab_bundles.py documents and which was
tested in Chromium. A <script src> tag is not refused, so the index assigns
itself to a global and is injected on the first search rather than on load.

What is indexed:
  lesson   title and kicker, 35
  section  every h2 heading, 455
  check    the 296 review checklist items, by id, title and detail
  term     the 173 glossary terms and their definitions
  control  the Standard, Baseline and Option items in each reference layer
  code     every distinct identifier in a <code> span, per lesson

Not the lesson body prose. That is 104,002 words and would cost more than the
whole client bundle. The first version of this tool stopped at the first four
kinds, on the reasoning that a header name would be in them. It is not:
searching Access-Control-Allow-Credentials returned nothing, because header
names live in the reference controls and in code spans. Hence the last two.

Usage:
    python3 tools/build_search_index.py            # write it
    python3 tools/build_search_index.py --check    # exit 1 if stale
"""

import gzip
import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = ROOT / "assets" / "search-index.js"

HEADER = ("// Generated by tools/build_search_index.py from content/.\n"
          "// Do not edit. Loaded on the first search, never on page load.\n")


def plain(markup):
    return re.sub(r"\s+", " ",
                  html.unescape(re.sub(r"<[^>]+>", " ", markup))).strip()


def documents():
    lessons = [json.loads(p.read_text(encoding="utf-8"))
               for p in sorted((ROOT / "content" / "lessons").glob("*.json"))]
    index = json.loads((ROOT / "content" / "index.json").read_text(encoding="utf-8"))
    pages = json.loads((ROOT / "content" / "pages.json").read_text(encoding="utf-8"))
    by_slug = {entry["slug"]: entry for entry in index["lessons"]}

    docs = []
    for record in lessons:
        entry = by_slug[record["slug"]]
        docs.append({"k": "lesson", "s": record["slug"],
                     "t": plain(record["title"]), "m": entry["module"],
                     "x": plain(record["kicker"])})
        for section in record["sections"]:
            heading = section["heading_text"]
            if not heading:
                continue
            docs.append({"k": "section", "s": record["slug"], "t": heading,
                         "m": entry["module"], "x": plain(record["title"])})
        for check in record["checks"]:
            docs.append({"k": "check", "s": record["slug"],
                         "t": plain(check["title"]), "i": check["id"],
                         "v": check["severity"], "x": plain(check["detail"])})
    for record in lessons:
        entry = by_slug[record["slug"]]
        body = "".join(section["html"] for section in record["sections"])
        for level, label, text in re.findall(
                r'<li><span class="label (std|base|opt)">([^<]*)</span>(.*?)</li>',
                body, re.S):
            docs.append({"k": "control", "s": record["slug"],
                         "m": entry["module"], "v": label, "t": plain(text)})
        seen = set()
        for span in re.findall(r"<code>(.*?)</code>", body, re.S):
            word = plain(span)
            if 2 < len(word) < 60 and word not in seen:
                seen.add(word)
                docs.append({"k": "code", "s": record["slug"],
                             "m": entry["module"], "t": word})

    for term in pages["glossary"]["terms"]:
        docs.append({"k": "term", "s": term["id"], "t": plain(term["term"]),
                     "x": plain(term["definition"])})
    return docs


def bundle(docs):
    return (HEADER + "window.__searchIndex = "
            + json.dumps(docs, ensure_ascii=False, separators=(",", ":"))
            + ";\n")


def report(docs, text):
    kinds = {}
    for doc in docs:
        kinds[doc["k"]] = kinds.get(doc["k"], 0) + 1
    for kind in sorted(kinds):
        print("  %-9s %4d" % (kind, kinds[kind]))
    print("  %-9s %4d" % ("total", len(docs)))
    raw = len(text.encode("utf-8"))
    print("  %-9s %6.1f KB raw, %.1f KB gzipped"
          % ("size", raw / 1024, len(gzip.compress(text.encode("utf-8"))) / 1024))


def check():
    docs = documents()
    text = bundle(docs)
    print("build_search_index --check")
    report(docs, text)
    problems = []
    if not TARGET.is_file():
        problems.append("assets/search-index.js is missing")
    elif TARGET.read_text(encoding="utf-8") != text:
        problems.append("assets/search-index.js is out of date")
    ids = [d["i"] for d in docs if d["k"] == "check"]
    if len(ids) != len(set(ids)):
        problems.append("duplicate check ids in the index")
    if problems:
        print("\nrun python3 tools/build_search_index.py")
        for p in problems:
            print("  " + p)
        return 1
    print("\nthe search index matches content/")
    return 0


def write():
    docs = documents()
    text = bundle(docs)
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text, encoding="utf-8")
    print("wrote assets/search-index.js")
    report(docs, text)
    return 0


def main():
    if "--check" in sys.argv[1:]:
        return check()
    return write()


if __name__ == "__main__":
    sys.exit(main())
